# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Multilines' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multilines
  pod 'IGListKit', '~> 3.0'

  target 'MultilinesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultilinesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
